### ISSUE TITLE
consider: mention on-link relays might do validation

### ISSUE THREAD

**Issue by ekline** [wkumari/draft-wkumari-dhc-addr-notification#11]
Since some vendor is going to do it anyway, better perhaps to mention the concept here to head off any stupid IPR filing.

The basic idea: if an on-link relay has knowledge of this message and access to neighbor table state it may perform some validation checks on the contents of the addr reg message.

**Comment by wkumari** [comment]
Any suggested text?

**Comment by lcolitti** [comment]
We already say this:

If a network is using FCFS SAVI [RFC6620], then the DHCPv6 server can trust that the ADDR-REG-INFORM message was sent by the legitimate owner of the address. This prevents a host from registering an address owned by another host.

Do we need more text? Any suggestions?

**Comment by ekline** [comment]
Perfetto
