### ISSUE TITLE
Conflicting sentences re: refresh

### ISSUE THREAD

**Issue by furry13** [wkumari/draft-wkumari-dhc-addr-notification#19]
Section 5.2:
"It is RECOMMENDED that clients initiate a refresh at about 85% of the preferred lifetime. "

Section 5.3:
"The client MUST refresh the registration when 1/3 of the Preferred Lifetime of the address has elapsed. Such retransmissions should be jittered."

**Comment by wkumari** [comment]
PR #21 addressed this, closing.
