### ISSUE TITLE
Message acknowledgement

### ISSUE THREAD

**Issue by furry13** [wkumari/draft-wkumari-dhc-addr-notification#2]
Do we really need that 'server MUST acknowledge'? As the client has no way to know if the server supports it or not, the only benefit it might save the client sending 4 packets (as it's supposed to retransmit up to 4 times).
Also, the idea of ACK might lead to a rather undesirable idea of 'NACK' so the server has some authority to prevent the host from using the address.

IMHO the client shall just send N (default = 3?) packets with X seconds (default: X = 1)  between.

**Comment by wkumari** [comment]
Cleanup -- already addressed in PR #6.
