### ISSUE TITLE
Suggestion: A way for a client to tell the server that it is leaving.

### ISSUE THREAD

**Issue by wkumari** [wkumari/draft-wkumari-dhc-addr-notification#30]
The client MAY inform the server ....

**Comment by wkumari** [comment]
Acknowledge: Éric Levy-Abegnoli, Ted Lemon, Suresh Krishnan, Ryan Globus, Timothy Winter, Bernie Volz

**Comment by furry13** [comment]
How are we going to do this? We can either define a new option or set valid lifetime to 0 in IA Address option in the message..
I can put some text for the latter.

**Comment by furry13** [comment]
https://github.com/wkumari/draft-wkumari-dhc-addr-notification/commit/aa167d344afc2e271e82c6111dc29d7d58873937
