### ISSUE TITLE
Suggestion: If the Server sends an ACK, then the client can stop transmitting. 

### ISSUE THREAD

**Issue by wkumari** [wkumari/draft-wkumari-dhc-addr-notification#31]
"It should be noted that ADDR-REG-NOTIFICATION is the first and the only DHCPv6 message which does not require any form of acknowledgement from the server, so the retransmission logic described in Section 15 of RFC8415 is not really applicable."

Perhaps add: If the client *does* receive an acknowledgement, it should stop sending ... something.

From minutes: https://datatracker.ietf.org/doc/minutes-115-dhc-202211081630/

**Comment by wkumari** [comment]
From minutes: [Ryan Globus] a boolean from the server might be helpful,
optional not required, as an ack

**Comment by wkumari** [comment]
/we need to make it clear that the acknowledgment is **only** that the server has received the message. It is **not** permission to use the address or not -- this is just "yes, I heard you", not "yes, I agree"

**Comment by furry13** [comment]
I assume we need to use REPLY message for this?
In that case we might need to update RFC8415, as it says:
https://www.rfc-editor.org/rfc/rfc8415.html#section-7.3

REPLY (7)                 A server sends a Reply message containing
                             assigned leases and configuration
                             parameters in response to a Solicit,
                             Request, Renew, or Rebind message received
                             from a client.  A server sends a Reply
                             message containing configuration parameters
                             in response to an Information-request
                             message.  A server sends a Reply message in
                             response to a Confirm message confirming or
                             denying that the addresses assigned to the
                             client are appropriate to the link to which
                             the client is connected.  A server sends a
                             Reply message to acknowledge receipt of a
                             Release or Decline message.

**Comment by furry13** [comment]
https://github.com/wkumari/draft-wkumari-dhc-addr-notification/commit/d7ac3fbaa18d7eda6a88c0a0b5f8a5b7f813c101

**Comment by wkumari** [comment]
It *feels* like this might fall under the spirit of "A server sends a Reply message to acknowledge receipt of a
Release or Decline message." It feels like this is conceptually similar to "acknowledge receipt"....

Closing for now, we can re-open if people are unhappy.

Thank you, Jen!
