### ISSUE TITLE
Document behaviour of switches/relays that forward the message

### ISSUE THREAD

**Issue by lcolitti** [wkumari/draft-wkumari-dhc-addr-notification#35]
1. Document how relays forward the message. Though we already say:

DHCPv6 relay agents that relay address registration messages directly from clients SHOULD include the client's link-layer address in the relayed message using the Client Link-Layer Address option ([RFC6939])

2. Ensure that switches and relays do not do anything special (e.g., update DHCPv6 binding tables) when they see a REPLY..

**Comment by eqvinox** [comment]
2 points essentially:

- SAVI enabled switches / switches doing DHCPv6 inspection and possibly adding e.g. Option 82 to packets passing through MAY perform this action on ADDR-REG-INFORM packets.

- same devices MUST NOT perform any action upon inspecting a pass-through REPLY for an ADDR-REG-INFORM. In general, the devices will (a) only inspect multicast packets anyway (which this would not be?) and (b) won't act on unknown messages in REPLY, but this should be explicit.

**Comment by lcolitti** [comment]
SGTM. To the second stipulation seems best worded as "In particular, they MUST NOT install any forwarding state based on the REPLY message."

**Comment by eqvinox** [comment]
Forwarding state or filtering state (latter on SAVI switches)

**Comment by furry13** [comment]
>SAVI enabled switches / switches doing DHCPv6 inspection and possibly adding e.g. Option 82 to packets passing through MAY perform this action on ADDR-REG-INFORM packets.


Option82 is OPTION_SOL_MAX_RT - could you pls elaborate on this comment?

**Comment by furry13** [comment]
The first part addressed by https://github.com/wkumari/draft-wkumari-dhc-addr-notification/commit/6f13d9fc3d32e4d6274f5519a96bc198c8678ff1

**Comment by eqvinox** [comment]
Ah crap sorry option 82 is DHCPv4. I don't actually know if any switches do this with DHCPv6. If they do, it's probably option 35.

**Comment by lcolitti** [comment]
Isn't this built in to DHCPv6? The relay-forward message contains the client link address.

https://www.rfc-editor.org/rfc/rfc8415#section-9.1

**Comment by eqvinox** [comment]
Except option 35 was removed; I think it's just the relay agent ID now (53)

**Comment by eqvinox** [comment]
> Except option 35 was removed; I think it's just the relay agent ID now (53)

AFAICS it's options 18 (required) and 37 (optional) that switches insert… and this took way longer to find than I'm willing to admit :disappointed: … the behavior is described in [RFC6221](https://www.rfc-editor.org/rfc/rfc6221) aka LDRA. Unlike DHCPv4, where Option 82 is just inserted mid-packet, for DHCPv6 the switch does the full `RELAY-FORWARD` wrapping.

I guess since they're actual relays, switches don't need special distinction from relays (sorry for that confusion :face_with_spiral_eyes:), and it's just normal relay processing.
