### ISSUE TITLE
1 Message per address vs all addresses in a single message

### ISSUE THREAD

**Issue by furry13** [wkumari/draft-wkumari-dhc-addr-notification#4]
I see two ways:
- every time a host send a registration message it includes all addresses configured on the interface. 
Pros: allow explicit deprecations
Cons: allows an attacker to register an address even if it can't send pakcets from that address (by including it into the registration message)

- each message contains one address only - the address being registered.
 -- Pros: additional safety net: if the host can't send a packet from that address (e.g.SAVI) - it can't register the address.
 -- Cons: no explicit deprecation (but we can add another message for this, if needed)

**Comment by lcolitti** [comment]
We decided a long time ago to send the message from the address being registered so that L2 security could protect it.
