### ISSUE TITLE
Having flags to indicate address properties

### ISSUE THREAD

**Issue by furry13** [wkumari/draft-wkumari-dhc-addr-notification#5]
It might be useful to indicate address properties (e.g. stable vs temporary), so maybe we need a field to include this.
Smth like flags field?

**Comment by ekline** [comment]
IA_TA (temporary addrress) and IA_NA (non-temporary address) option types already include this 1-bit distinguishing information...

**Comment by wkumari** [comment]
I'm unclear what the resolution here is. Anything needed to be done?
