### ISSUE TITLE
support router originated registrations on behalf of clients?

### ISSUE THREAD

**Issue by ekline** [wkumari/draft-wkumari-dhc-addr-notification#9]
Question: should there be a mechanism to allow routers to generate registration messages for {L2,L3} pairs is has in its neighbor table?

Such a mechanism:

  * might reuse the same message type or use a new message type
  * would allow updated routers to contribute to debugging data while serving clients that don't support this option
  * might further overload a server on networks where client support for this behaviour is already robust
  * would need to tackle exactly what DUID should be generated by a router for these synthesized messages

**Comment by lcolitti** [comment]
This came up again in the wg. One of the issues was that the switch/relay can't really not know if the host is going to send an ADDR-REG-INFORM. If the switch/relay sends it, then the server might receive two messages for the same address from two different DUIDs. Also, the switch/relay probably won't know what options the client would put in the request - in particular, the FQDN option.

There seemed to be consensus in the room not to add anything to the draft for now.
